# Generated by Django 3.0 on 2019-12-15 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20191215_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescore',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance'),
        ),
    ]
