# Generated by Django 3.0 on 2019-12-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20191215_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancescore',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance'),
        ),
    ]
