# Generated by Django 3.0 on 2019-12-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatementer',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidatementer',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserRole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
